#!/usr/bin/env python3
"""F1's live end-to-end arm: write the request, gate what the real path returns.

Slice A of `docs/agents/qa-e2e-implementation.md`, and only that: one fixture,
one truth model, no framework. The document's section 13 says so in as many
words -- *do not implement them in one giant abstraction-first PR* -- and its
section 3 is the reason it matters here. F1 is a **reference-determined** design
(section 3.1); F2 is functional with many valid answers and F4 is preservation,
and a shell generalised across the three before any of them has run would be
generalising imagined requirements. So everything below names the grid bin.

**What this module is for.** `tools/blind.py` asks the corpus a question and
scores four dimensional measurements plus one shape descriptor. That is not
enough for F1, and not because the scorer is weak: F1's request is *a
specification*, and the acceptance is *did you build what the standard says* --
divider count, divider axis, lip present, forbidden features absent. Those are
topological facts about a solid and no bounding box can see them.

It is also deliberately **not** routed through `corpus.request_view`.
`tools/corpus.py`'s wall answers one question -- *does this requirement measure
a declared counterpart, or the part itself* -- and it is the right question for a
reconstruct-from-what-it-fits benchmark. F1 states `divider_count` and
`stack_lip`, which measure the part and are exactly what a requester
legitimately asks for, so that rule would refuse a valid request. What is reused
is the half that does transfer, and it is the strongest half:
`corpus.numbers_in` and `corpus.coincidences` audit **this** request against the
reference's own measurements, so a number that leaked into the brief is a hard
failure here for the same reason it is there.

**The requester-side prohibition is structural, not a promise.** The boundary
includes derived measurements, not just the reference mesh: on the bee fixture
the designer voluntarily avoided the measurement scripts, and a harness that
depends on that restraint is measuring the designer's manners. `audit_request`
compares every number in the materialised request package against the
reference's extents and volume and refuses an undeclared coincidence. What it
cannot do is stop a designer reading the reference off the filesystem, so the
run also puts the working directory somewhere with no path to it; the two
together are the boundary, and `score()` records which of them was in force.

**Registration fits translation and a proper rotation, and nothing else.**
Section 4 of the brief: no scaling, no reflection, `det(R) = +1`. The pose set
here is the 24 proper rotations of a cuboid rather than a fitted ICP, because
this fixture's parts are axis-aligned prisms and an unconstrained fitter is
exactly what erases a handedness error. `PROPER_ROTATIONS` is generated by
filtering the 48 signed permutations on determinant, so the improper half is
absent by construction rather than by a comment.

**Every band is calibrated from same-geometry noise.** Section 5, and the
numbers live in `benchmarks/e2e/f1-gridbin.json` under `calibration` with the
method that produced them. Nothing in this file chooses a tolerance.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import os
import sys
import time
import zipfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "skills" / "3d-modeling" / "scripts"))
sys.path.insert(0, str(ROOT / "tools"))

import corpus                                                    # noqa: E402

FIXTURE = ROOT / "benchmarks" / "e2e" / "f1-gridbin.json"


class E2EError(RuntimeError):
    """The fixture cannot be run as asked. Never a low score."""


class ReferenceUnavailable(corpus.CorpusUnavailable):
    """The hidden reference is not on this machine.

    Subclasses `corpus.CorpusUnavailable` rather than repeating it, so a caller
    that already handles a missing corpus handles a missing E2E reference by the
    same clause. `corpus.resolve` itself does not fit: it addresses a *fetched
    git source*, and this reference is generated by a pinned third-party
    generator into the project tree. What transfers is the discipline -- the
    digest is checked on every call, and absence is loud rather than a skip.
    """


class ReferenceCorrupt(corpus.CorpusCorrupt):
    """The reference is present and is not the bytes the fixture names."""


class RequestLeak(corpus.CorpusLeak):
    """The request package states one of the reference's own measurements."""


# --------------------------------------------------------------------------
# The fixture, and the reference it must never hand over
# --------------------------------------------------------------------------

def fixture(path: Path | None = None) -> dict[str, Any]:
    return json.loads(Path(path or FIXTURE).read_text(encoding="utf-8"))


def scorer_commit() -> str | None:
    """The commit this scorer is, or None when that cannot be established.

    Brief section 10 requires the run report to bind the scorer's version
    alongside the candidate and reference digests, and it is the one binding a
    report cannot reconstruct later: two runs of the same candidate against the
    same reference can disagree, and without this there is nothing in the
    payload that says which scorer produced which.

    `None` rather than a guess when the tree is dirty or git cannot answer. A
    commit id printed beside uncommitted changes is a stronger claim than the
    evidence supports -- it says "this is the code that ran" about code that is
    not what ran.
    """
    import subprocess

    try:
        head = subprocess.run(["git", "-c", "safe.directory=*", "rev-parse",
                               "HEAD"], cwd=str(ROOT), capture_output=True,
                              text=True, check=False)
        dirty = subprocess.run(["git", "-c", "safe.directory=*", "status",
                                "--porcelain"], cwd=str(ROOT),
                               capture_output=True, text=True, check=False)
    except OSError:
        return None
    if head.returncode != 0 or dirty.returncode != 0:
        return None
    if dirty.stdout.strip():
        return None
    return head.stdout.strip() or None


def _digest(path: Path) -> str:
    reader = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            reader.update(block)
    return reader.hexdigest()


def reference_path(spec: dict[str, Any] | None = None) -> Path:
    """Where the scored reference is, proven to be the bytes the fixture names.

    Verified on every call, not once at ingest. A digest checked when the file
    was generated says nothing about the file this run is about to read, and the
    cost is a hash of a file already in the page cache -- the argument
    `corpus.resolve` makes, and the property that makes a drifted reference a
    loud failure instead of a different answer.
    """
    spec = spec or fixture()
    block = spec["reference"]
    root = Path(os.environ.get(block["root"]["env"], block["root"]["default"]))
    path = (root / block["path"]).expanduser()
    if not path.is_file():
        raise ReferenceUnavailable(
            f"{spec['id']}'s reference is not at {path}. It is generated, not "
            f"fetched: {block['generator']['install']} then "
            f"{block['generator']['call']}, normalised through "
            f"mesh_io.normalize_mesh. Set {block['root']['env']} if it lives "
            "elsewhere.")
    found = _digest(path)
    if found != block["sha256"]:
        raise ReferenceCorrupt(
            f"{spec['id']}'s reference at {path} hashes {found[:12]} and the "
            f"fixture names {block['sha256'][:12]}. A benchmark scored against "
            "a drifted reference produces a number indistinguishable from a "
            "real one.")
    return path


# --------------------------------------------------------------------------
# The request side
# --------------------------------------------------------------------------

def write_request(spec: dict[str, Any], into: Path) -> Path:
    """Lay the question down as a directory the real design path can be run in.

    The brief is carried verbatim from the fixture rather than composed here:
    it is the one artifact a designer reads, so it is reviewable as text in the
    diff that freezes it, not as the output of a formatter nobody runs.
    """
    into = Path(into)
    (into / "request").mkdir(parents=True, exist_ok=True)
    brief = "\n".join(spec["request"]["brief"]) + "\n"
    (into / "request" / "brief.md").write_text(brief, encoding="utf-8",
                                               newline="\n")
    (into / "request" / "project.json").write_text(
        json.dumps(spec["request"]["project"], indent=2, sort_keys=True) + "\n",
        encoding="utf-8", newline="\n")
    return into / "request"


def audit_request(spec: dict[str, Any], request_dir: Path,
                  measured: dict[str, float]) -> dict[str, Any]:
    """Refuse a request package that states one of the reference's own numbers.

    `corpus.numbers_in` and `corpus.coincidences`, applied to the bytes a
    designer is actually handed rather than to the manifest that produced them
    -- a rule enforced on the manifest and not on its output is a rule about a
    file nobody reads (`tools/test_blind.py`'s own words).

    One coincidence is *declared* and it is the reason this function returns a
    record instead of only raising. The published grid pitch is 42 mm and a
    one-unit-wide bin is one pitch less the standard clearance, so a requester
    who states the pitch -- which is the only way the request is answerable at
    all -- necessarily states the short footprint to within 1.2%. That is
    `docs/defects.md` D30's shape exactly, and it is declared in the fixture
    with the public source a reader can check. Everything undeclared is refused.
    """
    declared = {row["measurement"] for row in spec["request"].get("discloses", ())}
    text = "\n".join(sorted(p.read_text(encoding="utf-8")
                            for p in sorted(Path(request_dir).rglob("*"))
                            if p.is_file()))
    found = corpus.coincidences(corpus.numbers_in(text), measured)
    undeclared = [pair for pair in found if pair[1] not in declared]
    if undeclared:
        detail = "; ".join(f"{value:g} is the reference's {name}"
                           for value, name in undeclared)
        raise RequestLeak(
            f"{spec['id']}: the request package states a measurement of the "
            f"reference itself -- {detail}. The prohibition covers derived "
            "measurements, not only the mesh: declare it in the fixture with a "
            "public source, or take it out of the brief.")
    # A disclosure that gives away nothing is an exemption with a sentence
    # attached, and it would excuse that axis for every future edit of this
    # fixture -- `corpus.request_view` refuses one for that reason and so does
    # this.
    spurious = sorted(declared - {name for _, name in found})
    if spurious:
        raise RequestLeak(
            f"{spec['id']}: discloses {', '.join(spurious)}, and the request "
            "states no number that measures it.")
    return {"coincidences": [[value, name] for value, name in found],
            "declared": sorted(declared)}


# --------------------------------------------------------------------------
# Measurement
# --------------------------------------------------------------------------

def load(path: Path):
    import trimesh
    return trimesh.load(str(path), force="mesh")


def _rings(mesh, z: float) -> list[Any]:
    """The cavity cross-sections at height `z`, as shapely polygons.

    A horizontal slice of a bin is one filled outline with a hole per open
    compartment, so the *interior rings* are the compartments and counting them
    is how divider count is measured without a CAD feature tree. `to_2D` is
    given an explicit transform: its default picks its own planar frame, and a
    frame chosen by the library would make "the divider is on the long axis" a
    statement about whichever basis trimesh happened to return.
    """
    import numpy as np
    from shapely.geometry import Polygon

    section = mesh.section(plane_origin=[0.0, 0.0, z], plane_normal=[0, 0, 1])
    if section is None:
        return []
    world_to_plane = np.eye(4)
    world_to_plane[2, 3] = -z
    flat, _ = section.to_2D(to_2D=world_to_plane)
    return [Polygon(interior) for shape in flat.polygons_full
            for interior in shape.interiors]


def _outer_area(mesh, z: float) -> float:
    import numpy as np
    from shapely.geometry import Polygon

    section = mesh.section(plane_origin=[0.0, 0.0, z], plane_normal=[0, 0, 1])
    if section is None:
        return 0.0
    world_to_plane = np.eye(4)
    world_to_plane[2, 3] = -z
    flat, _ = section.to_2D(to_2D=world_to_plane)
    return float(sum(Polygon(shape.exterior).area
                     for shape in flat.polygons_full))


def _band(low: float, high: float, step: float) -> list[float]:
    """Sample heights, inclusive of both ends and deterministic.

    Deterministic because the prismatic and lip predicates are *comparisons
    between heights*: a sample set that moved between runs would make a passing
    candidate fail on the next invocation for no reason a reader could find.
    """
    if high < low:
        return []
    count = max(1, int(round((high - low) / step)))
    return [low + (high - low) * i / count for i in range(count + 1)]


def features(mesh, geometry: dict[str, Any]) -> dict[str, Any]:
    """Everything the F1 predicates read, measured once off one solid.

    Bands are placed relative to the candidate's **own** top rather than at
    absolute heights, because a candidate that got the height wrong should fail
    the height predicate and still have its divider and its lip measured -- a
    band pinned to the reference's 24.8 mm would report a short bin as having no
    compartments, which blames the wrong thing.
    """
    low, high = mesh.bounds[0], mesh.bounds[1]
    z0, top = float(low[2]), float(high[2])
    height = top - z0
    step = geometry["section_step_mm"]

    base = geometry["base_band"]
    base_zs = _band(z0 + base["low_mm"], z0 + base["high_mm"], step)
    base_rings = [len(_rings(mesh, z)) for z in base_zs]

    comp = geometry["compartment_band"]
    comp_zs = _band(z0 + comp["above_floor_mm"], top - comp["below_top_mm"], step)
    comp_rings = [_rings(mesh, z) for z in comp_zs]
    comp_counts = [len(r) for r in comp_rings]
    comp_areas = [float(sum(p.area for p in r)) for r in comp_rings]
    comp_inner = [_inner_box(r) for r in comp_rings]
    comp_outer = [_outer_area(mesh, z) for z in comp_zs]

    lip = geometry["lip_band"]
    lip_zs = _band(top - lip["below_top_low_mm"], top - lip["below_top_high_mm"],
                   step)
    lip_inner = [_inner_box(_rings(mesh, z)) for z in lip_zs]
    lip_outer = [_outer_area(mesh, z) for z in lip_zs]

    return {
        "height_mm": height,
        "extents_mm": [float(v) for v in mesh.extents],
        "volume_mm3": float(mesh.volume),
        "bodies": int(mesh.body_count),
        "watertight": bool(mesh.is_watertight),
        "base_band_z": base_zs, "base_ring_counts": base_rings,
        "compartment_band_z": comp_zs,
        "compartment_ring_counts": comp_counts,
        "compartment_cavity_area_mm2": comp_areas,
        "compartment_inner_box_mm": comp_inner,
        "compartment_outer_area_mm2": comp_outer,
        "lip_band_z": lip_zs,
        "lip_inner_box_mm": lip_inner,
        "lip_outer_area_mm2": lip_outer,
        "split": _split(comp_rings),
    }


def _inner_box(rings: list[Any]) -> list[float]:
    """The overall opening at one height: the union bbox of every cavity.

    Union rather than per-cavity, so a divider -- which sits *inside* the
    opening -- does not change it. That is what lets the lip predicate compare
    a height with two compartments against a height with one.
    """
    if not rings:
        return [0.0, 0.0]
    xs = [v for ring in rings for v in (ring.bounds[0], ring.bounds[2])]
    ys = [v for ring in rings for v in (ring.bounds[1], ring.bounds[3])]
    return [max(xs) - min(xs), max(ys) - min(ys)]


def _split(bands: list[list[Any]]) -> dict[str, Any] | None:
    """Which axis the compartments are divided along, from their footprints.

    Decided by *disjointness*, not by comparing centroids. Two compartments
    either side of an x-normal divider have disjoint x ranges and identical y
    ranges; centroids alone say the same thing far more weakly, because a pair
    of L-shaped cavities can have separated centroids on an axis neither of them
    is divided along.
    """
    two = [rings for rings in bands if len(rings) == 2]
    if not two:
        return None
    rings = two[len(two) // 2]
    a, b = sorted(rings, key=lambda r: r.bounds[0] + r.bounds[1])
    gap_x = b.bounds[0] - a.bounds[2]
    gap_y = b.bounds[1] - a.bounds[3]
    return {"gap_x_mm": float(gap_x), "gap_y_mm": float(gap_y),
            "axis": "x" if gap_x > gap_y else "y"}


# --------------------------------------------------------------------------
# Registration and surface distance
# --------------------------------------------------------------------------

def _proper_rotations():
    """The 24 proper rotations of a cuboid, and not the 24 improper ones.

    Generated by filtering the 48 signed permutation matrices on
    `det = +1`, so the reflections are absent by construction. Brief section 4:
    *a mirrored part must not become a PASS because a fitter found a
    reflection.* A tolerance-based rule would be the wrong instrument -- a
    reflection is not a near miss of a rotation, it is a different group coset,
    and the determinant is exactly one or exactly minus one.
    """
    import numpy as np

    out = []
    for perm in itertools.permutations(range(3)):
        for signs in itertools.product((1.0, -1.0), repeat=3):
            matrix = np.zeros((3, 3))
            for row, col in enumerate(perm):
                matrix[row, col] = signs[row]
            if round(float(np.linalg.det(matrix))) == 1:
                out.append(matrix)
    return out


def surface_distance(a, b, *, samples: int, seed: int, band_mm: float
                     ) -> dict[str, float]:
    """Bidirectional sampled surface distance between two meshes.

    Both directions, because a one-way nearest-neighbour score is blind in the
    direction that matters most here: every point of a bin with an extra
    protrusion still has a near neighbour on the bin without one, so A->B stays
    small while B->A does not. Brief section 4.6 requires both and this is why.

    Deterministic: the sample seed is frozen in the fixture, so two runs of the
    same pair produce the same distribution and a changed number means changed
    geometry.
    """
    import numpy as np
    import trimesh

    pa = trimesh.sample.sample_surface(a, samples, seed=seed)[0]
    pb = trimesh.sample.sample_surface(b, samples, seed=seed)[0]
    da = trimesh.proximity.closest_point(b, pa)[1]
    db = trimesh.proximity.closest_point(a, pb)[1]
    both = np.concatenate([np.asarray(da, dtype=float),
                           np.asarray(db, dtype=float)])
    return {
        "samples": int(both.size),
        "median_mm": float(np.median(both)),
        "mean_mm": float(np.mean(both)),
        "p95_mm": float(np.percentile(both, 95)),
        "p99_mm": float(np.percentile(both, 99)),
        "max_mm": float(np.max(both)),
        "fraction_within_band": float(np.mean(both <= band_mm)),
    }


def register(candidate, reference, *, samples: int, seed: int, band_mm: float,
             probe_samples: int = 1500) -> dict[str, Any]:
    """Translation plus one proper rotation, chosen by measured distance.

    The candidate is centred on its own bounding box and the reference on its
    own, then each of the 24 proper rotations is scored on a cheap probe sample
    and the best is re-measured at full count. No scaling is fitted and no
    reflection is available, so a mirrored candidate cannot be rotated into
    agreement -- it is scored as the mismatch it is.

    Centring on the bounding box rather than the centre of mass is deliberate:
    a centre of mass moves when a feature is removed, so a missing divider would
    partly hide itself by shifting the fit. A bounding box moves only when the
    envelope changes, which is a thing the extents predicate reports separately.
    """
    import numpy as np

    fixed = reference.copy()
    fixed.apply_translation(-reference.bounding_box.centroid)
    want = np.asarray(reference.extents, dtype=float)
    have = np.asarray(candidate.extents, dtype=float)

    # Poses whose rotated bounding box does not match the reference's cannot be
    # the alignment, so they are not measured. This is a cost decision with a
    # correctness floor under it: when *no* pose matches -- a candidate with the
    # wrong extents, which is a thing the extents predicates report separately
    # -- every pose is tried, so the fallback is the full group rather than an
    # empty set and an exception.
    # Generous on purpose, and much wider than the acceptance band: this filter
    # decides which way up the part is, not whether it is right. A tolerance of
    # the acceptance band would drop the correct pose for a candidate that is
    # merely a millimetre off, and the fallback below would then measure all 24.
    slack = 0.05 * float(np.max(want))
    poses = [(index, rotation) for index, rotation
             in enumerate(_proper_rotations())
             if np.allclose(np.abs(rotation @ have), want, atol=slack)]
    if not poses:
        poses = list(enumerate(_proper_rotations()))

    best = None
    for index, rotation in poses:
        moved = candidate.copy()
        moved.apply_translation(-candidate.bounding_box.centroid)
        transform = np.eye(4)
        transform[:3, :3] = rotation
        moved.apply_transform(transform)
        probe = surface_distance(moved, fixed, samples=probe_samples, seed=seed,
                                 band_mm=band_mm)
        # The MEAN, not the median. Measured: a two percent single-axis scale --
        # a defect a metre away is visible in -- has a median distance of
        # 5e-15 mm, because most of a sampled surface still lands on the other
        # surface. The median cannot choose a pose; the mean separates the same
        # pair by five orders of magnitude.
        if best is None or probe["mean_mm"] < best[1]["mean_mm"]:
            best = (index, probe, transform, moved)
    index, _, transform, moved = best
    full = surface_distance(moved, fixed, samples=samples, seed=seed,
                            band_mm=band_mm)
    return {"pose_index": index,
            "rotation": [[float(v) for v in row] for row in transform[:3, :3]],
            "determinant": round(float(np.linalg.det(transform[:3, :3])), 9),
            "distance": full}


# --------------------------------------------------------------------------
# The hard predicates. Candidate-independent, and frozen before any run.
# --------------------------------------------------------------------------

def _row(name: str, ok: bool | None, got: Any, want: str, why: str = ""
         ) -> dict[str, Any]:
    return {"predicate": name, "passes": ok, "measured": got,
            "required": want, "why": why}


def predicates(got: dict[str, Any], geometry: dict[str, Any]
               ) -> list[dict[str, Any]]:
    """Every hard predicate that reads the candidate alone.

    Split from the reference comparison because they answer different
    questions and fail for different reasons. These say *is this the thing the
    brief asked for*; the comparison says *is it the same solid*. A fixture
    that reported one number for both would hide which.
    """
    pitch = geometry["grid_pitch_mm"]
    least = geometry["footprint_min_undersize_mm"]
    most = geometry["footprint_max_undersize_mm"]
    units_x, units_y = geometry["footprint_units"]
    extents = sorted(got["extents_mm"], reverse=True)

    def drops_into_the_grid(measured: float, units: int) -> bool:
        """Undersize by a working amount, rather than equal to a stated number.

        A cell of `units` pitches is the space available, so a bin that is
        exactly that wide binds and one that is a millimetre under rattles.
        Expressed as a band on the *undersize* because that is what the request
        gives -- the pitch and 'drops in and comes out again'. The alternative,
        `units * pitch - 0.5 +/- tol`, would need the published clearance to be
        exactly right, and it would put the reference's own 41.5 into the
        predicate as a target rather than deriving a requirement from the
        interface.
        """
        under = units * pitch - measured
        return least <= under <= most

    rows = [
        _row("one_printable_body", got["bodies"] == 1, got["bodies"], "1",
             "an extra solid in the STL is an extra thing on the plate"),
        _row("watertight", got["watertight"], got["watertight"], "True",
             "an open surface has no volume and no defensible moments"),
        _row("footprint_long_mm", drops_into_the_grid(extents[0], units_x),
             round(extents[0], 3),
             f"{units_x} x {pitch} mm less {least}..{most} mm",
             "the published pitch and the requirement that the bin drop into a "
             "cell and lift back out; no reference measurement is involved"),
        _row("footprint_short_mm", drops_into_the_grid(extents[1], units_y),
             round(extents[1], 3),
             f"{units_y} x {pitch} mm less {least}..{most} mm",
             "the published pitch and the requirement that the bin drop into a "
             "cell and lift back out; no reference measurement is involved"),
        _row("height_mm",
             geometry["height_min_mm"] <= got["height_mm"] <= geometry["height_max_mm"],
             round(got["height_mm"], 3),
             f"{geometry['height_min_mm']}..{geometry['height_max_mm']}",
             "the brief states three height units of 7 mm; the base and lip "
             "allowance on top of that is standard-defined and the band is "
             "deliberately wide, because narrowing it would encode the hidden "
             "reference's own total height"),
    ]

    counts = set(got["compartment_ring_counts"])
    want_compartments = geometry["expected_compartments"]
    rows.append(_row(
        "compartment_count", counts == {want_compartments},
        sorted(counts), f"{{{want_compartments}}} at every sampled height",
        "one divider makes two compartments, and it has to be two at every "
        "height in the band -- a divider that stops half way up is a divider "
        "at one sample and not at the next"))

    split = got["split"]
    rows.append(_row(
        "divider_on_long_axis", bool(split) and split["axis"] == geometry["split_axis"],
        split, f"axis {geometry['split_axis']}",
        "the brief asks for the long direction to be split; a divider on the "
        "short axis is one divider in the wrong place, which every count "
        "predicate above would accept"))

    base_bores = max(got["base_ring_counts"], default=0)
    rows.append(_row(
        "no_bores_in_base", base_bores == 0, base_bores, "0",
        "magnet pockets and screw holes are the only reason a closed base "
        "section has a hole in it, and the brief forbids both"))

    areas = got["compartment_cavity_area_mm2"]
    if areas:
        spread = (max(areas) - min(areas)) / max(areas)
    else:
        spread = 1.0
    rows.append(_row(
        "compartment_is_prismatic",
        bool(areas) and spread <= geometry["prismatic_tolerance_fraction"],
        round(spread, 5), f"<= {geometry['prismatic_tolerance_fraction']}",
        "a finger scoop is a ramp at the bottom of a compartment and a label "
        "flange is a tab at the top; both are forbidden and both show up as "
        "the open area changing with height, which a straight-walled "
        "compartment does not"))

    inner = got["compartment_inner_box_mm"]
    lip_inner = got["lip_inner_box_mm"]
    if inner and lip_inner:
        comp_x = max(box[0] for box in inner)
        comp_y = max(box[1] for box in inner)
        top_x = min(box[0] for box in lip_inner)
        top_y = min(box[1] for box in lip_inner)
        inset = min((comp_x - top_x) / 2.0, (comp_y - top_y) / 2.0)
    else:
        inset = 0.0
    rows.append(_row(
        "stack_lip_present", inset >= geometry["min_lip_inset_mm"],
        round(inset, 4), f">= {geometry['min_lip_inset_mm']} mm per side",
        "a stacking lip is a ledge that protrudes inward at the top so the "
        "base of the next bin lands on it, so the opening near the top is "
        "narrower than the compartment below it"))
    return rows


def outer_profile_drift(got: dict[str, Any]) -> float | None:
    """How much the outer cross-section grows between the wall and the rim.

    A **diagnostic**, and it started as a hard predicate. It was demoted for the
    reason section 12 of the brief gives: every predicate that can decide
    PASS/FAIL must have a mutation that proves it can fail, and this one has no
    failure of its own. A rim that flares outward grows the bounding box, so
    `footprint_long_mm` and `footprint_short_mm` already refuse it; a rim that
    grows the cross-section *without* growing the bounding box -- filling the
    corner radii, say -- is 0.35% on this footprint and is not a
    grid-compatibility failure at all. A gate nothing can fail reads exactly
    like one that holds, so it is reported and not gated.
    """
    comp = got["compartment_outer_area_mm2"]
    lip = got["lip_outer_area_mm2"]
    if not comp or not lip:
        return None
    return round(abs(max(lip) - max(comp)) / max(comp), 6)


def comparison_rows(registration: dict[str, Any], geometry: dict[str, Any]
                    ) -> list[dict[str, Any]]:
    band = geometry["reference_comparison"]
    distance = registration["distance"]
    return [
        _row("registration_is_a_proper_rotation",
             registration["determinant"] == 1.0, registration["determinant"],
             "det(R) = +1",
             "translation and a proper rotation only. No scaling and no "
             "reflection is available to the fitter, so a mirrored candidate "
             "is scored as the mismatch it is"),
        _row("reference_surface_distance_p99_mm",
             distance["p99_mm"] <= band["band_mm"],
             round(distance["p99_mm"], 4), f"<= {band['band_mm']} mm",
             "calibrated from same-geometry noise; see the fixture's "
             "calibration block for the method and what it cannot catch"),
    ]


# --------------------------------------------------------------------------
# The 3MF gate, separate from CAD
# --------------------------------------------------------------------------

_CORE_NS = "{http://schemas.microsoft.com/3dmanufacturing/core/2015/02}"


def read_three_mf(path: Path) -> dict[str, Any]:
    """The printable objects a 3MF actually places, read without `lxml`.

    `trimesh.load` cannot open a 3MF in this repository's default install:
    its loader needs `lxml`, which is only in the `bambu` extra, so the reload
    raises `ModuleNotFoundError` on a runtime-only sync. That is
    `docs/defects.md` D3 -- *the round-trip reload check has never executed in
    the frozen runtime* -- reproduced here, and it is why a 3MF gate that
    depended on `trimesh.load` would report the archive unreadable on every
    machine that had not selected an unrelated slicer extra.

    So the archive is read with the standard library. That is also the stricter
    reading: the build items are resolved through their components, so an extra
    body hidden as a second component of the placed assembly is counted, and an
    object that exists in `<resources>` but is never placed is not -- and those
    are two different findings that a concatenating loader merges into one mesh.
    """
    import numpy as np
    import trimesh
    from xml.etree import ElementTree

    with zipfile.ZipFile(path) as archive:
        name = next((n for n in archive.namelist()
                     if n.lower().endswith("3dmodel.model")), None)
        if name is None:
            raise E2EError(f"{path} has no 3D model part")
        root = ElementTree.fromstring(archive.read(name))

    unit = root.get("unit")
    meshes: dict[str, Any] = {}
    components: dict[str, list[tuple[str, Any]]] = {}
    for obj in root.iter(f"{_CORE_NS}object"):
        oid = obj.get("id")
        mesh = obj.find(f"{_CORE_NS}mesh")
        if mesh is not None:
            vertices = np.array(
                [[float(v.get("x")), float(v.get("y")), float(v.get("z"))]
                 for v in mesh.iter(f"{_CORE_NS}vertex")], dtype=float)
            faces = np.array(
                [[int(t.get("v1")), int(t.get("v2")), int(t.get("v3"))]
                 for t in mesh.iter(f"{_CORE_NS}triangle")], dtype=np.int64)
            meshes[oid] = trimesh.Trimesh(vertices=vertices, faces=faces,
                                          process=False)
        group = obj.find(f"{_CORE_NS}components")
        if group is not None:
            components[oid] = [(c.get("objectid"), _matrix(c.get("transform")))
                               for c in group.iter(f"{_CORE_NS}component")]

    placed: list[Any] = []

    def place(oid: str, transform, depth: int = 0) -> None:
        if depth > 8:                       # a components cycle, not a model
            raise E2EError(f"{path}: component nesting does not terminate")
        if oid in meshes:
            body = meshes[oid].copy()
            body.apply_transform(transform)
            placed.append(body)
        for child, child_transform in components.get(oid, ()):
            place(child, transform @ child_transform, depth + 1)

    items = list(root.iter(f"{_CORE_NS}item"))
    for item in items:
        place(item.get("objectid"), _matrix(item.get("transform")))
    return {"unit": unit, "build_items": len(items),
            "printable_bodies": len(placed),
            "resource_meshes": len(meshes), "bodies": placed}


def _matrix(raw: str | None):
    """A 3MF `transform` attribute as a 4x4, or the identity when absent.

    3MF writes the affine as twelve numbers in row-major order for a 4x3
    matrix whose last row is the translation, which is the transpose of what
    trimesh applies. Getting that backwards silently rotates a placed body, so
    it is written out rather than assumed.
    """
    import numpy as np

    out = np.eye(4)
    if not raw:
        return out
    values = [float(v) for v in raw.split()]
    if len(values) != 12:
        raise E2EError(f"a 3MF transform has twelve numbers, not {len(values)}")
    out[:3, :3] = np.array(values[:9], dtype=float).reshape(3, 3).T
    out[:3, 3] = values[9:]
    return out


def three_mf_rows(path: Path, accepted, geometry: dict[str, Any]
                  ) -> list[dict[str, Any]]:
    """3MF is a delivery gate and is reported apart from the CAD verdict.

    Brief section 2.2: no byte comparison, no ZIP metadata, no UUIDs, no object
    ordering. What is checked is that the archive is readable, places the
    printable objects the accepted STL set carries and no others, declares
    millimetres, and holds *this* geometry rather than an earlier export --
    which is the failure a stale 3MF produces and the one a body count cannot
    see.
    """
    path = Path(path) if path else None
    if path is None or not path.is_file():
        return [_row("three_mf_present", False, str(path), "a 3MF file",
                     "the brief requires one and the run did not produce it")]
    rows = [_row("three_mf_present", True, path.name, "a 3MF file", "")]
    try:
        read = read_three_mf(path)
    except (OSError, zipfile.BadZipFile, E2EError, ValueError) as exc:
        return rows + [_row("three_mf_readable", False, f"{type(exc).__name__}: "
                            f"{exc}", "a readable OPC archive", "")]
    rows.append(_row("three_mf_readable", True, "3D/3dmodel.model",
                     "3D/3dmodel.model", ""))
    rows.append(_row("three_mf_unit_is_millimetre", read["unit"] == "millimeter",
                     read["unit"], "millimeter",
                     "3MF's default unit is the micron, so an unstated or "
                     "wrong unit is a thousandfold scale error that no "
                     "geometry check would report as a unit problem"))
    rows.append(_row("three_mf_printable_body_count",
                     read["printable_bodies"] == 1, read["printable_bodies"],
                     "1",
                     "counted through the build items and their components, so "
                     "a second body welded into the placed assembly is a "
                     "finding rather than extra triangles in one mesh"))
    if not read["bodies"]:
        return rows + [_row("three_mf_matches_the_accepted_stl", False, 0,
                            "geometry", "the archive places nothing")]

    import trimesh

    loaded = trimesh.util.concatenate(read["bodies"])
    band = geometry["three_mf"]["band_mm"]
    distance = surface_distance(loaded, accepted,
                                samples=geometry["three_mf"]["samples"],
                                seed=geometry["reference_comparison"]["seed"],
                                band_mm=band)
    rows.append(_row("three_mf_matches_the_accepted_stl",
                     distance["p99_mm"] <= band, round(distance["p99_mm"], 6),
                     f"<= {band} mm",
                     "calibrated from an export/reload of the same geometry, "
                     "so this fails for a stale or substituted body and not "
                     "for the coordinate quantisation every export makes"))
    rows.append(_row("three_mf_volume_delta_mm3", True,
                     round(float(loaded.volume) - float(accepted.volume), 6),
                     "diagnostic", "reported, not gated"))
    return rows


# --------------------------------------------------------------------------
# The run report
# --------------------------------------------------------------------------

def score(candidate_stl: Path, three_mf: Path | None = None,
          spec: dict[str, Any] | None = None, *,
          request_dir: Path | None = None,
          design_path_seconds: float | None = None,
          authoring_root: str | None = None) -> dict[str, Any]:
    """Every hard predicate and every diagnostic, with the clock split in two.

    `PASS` is the conjunction of the hard predicates and never a weighted
    total, per brief section 10. `timings` reports the harness apart from the
    design path because the reviewer asked for them apart: a blended number
    cannot answer *is the benchmark expensive or is CAD expensive*, and those
    have different remedies.
    """
    clock: dict[str, float] = {}

    def timed(name: str, work):
        start = time.perf_counter()
        out = work()
        clock[name] = round(time.perf_counter() - start, 4)
        return out

    spec = spec or fixture()
    geometry = spec["geometry"]
    candidate_stl = Path(candidate_stl)
    if not candidate_stl.is_file():
        raise E2EError(f"no candidate at {candidate_stl}")

    reference = timed("resolve_reference", lambda: reference_path(spec))
    ref_mesh = timed("load_reference", lambda: load(reference))
    measured = timed("measure_reference", lambda: {
        "extent_x": float(ref_mesh.extents[0]),
        "extent_y": float(ref_mesh.extents[1]),
        "extent_z": float(ref_mesh.extents[2]),
        "volume_mm3": float(ref_mesh.volume)})

    leak = timed("audit_request",
                 lambda: audit_request(spec, request_dir, measured)
                 if request_dir else None)

    mesh = timed("load_candidate", lambda: load(candidate_stl))
    got = timed("measure_candidate", lambda: features(mesh, geometry))
    hard = timed("predicates", lambda: predicates(got, geometry))
    registration = timed("registration", lambda: register(
        mesh, ref_mesh,
        samples=geometry["reference_comparison"]["samples"],
        seed=geometry["reference_comparison"]["seed"],
        band_mm=geometry["reference_comparison"]["band_mm"]))
    hard += timed("comparison", lambda: comparison_rows(registration, geometry))
    mf = timed("three_mf", lambda: three_mf_rows(three_mf, mesh, geometry)
               if three_mf else [])

    cad_pass = all(row["passes"] for row in hard)
    mf_pass = all(row["passes"] for row in mf) if mf else None
    return {
        "schema_version": 1,
        "fixture": spec["id"],
        "fixture_revision": spec["revision"],
        "scorer": "tools/e2e.py",
        "scorer_commit": scorer_commit(),
        "candidate_stl_sha256": _digest(candidate_stl),
        "three_mf_sha256": _digest(Path(three_mf)) if three_mf and
        Path(three_mf).is_file() else None,
        "reference_sha256": spec["reference"]["sha256"],
        "verdict": ("CAD_PASS" if cad_pass else "CAD_FAIL") +
                   ("" if mf_pass is None else
                    (" / 3MF_PASS" if mf_pass else " / 3MF_FAIL")),
        "hard_predicates": hard,
        "three_mf": mf,
        "diagnostics": {
            "sorted_extents_mm": sorted(got["extents_mm"]),
            "volume_mm3": got["volume_mm3"],
            "reference_volume_mm3": measured["volume_mm3"],
            "surface_distance": registration["distance"],
            "pose_index": registration["pose_index"],
            "compartment_inner_box_mm": got["compartment_inner_box_mm"][:1],
            "cavity_area_mm2": got["compartment_cavity_area_mm2"][:1],
            "outer_profile_drift": outer_profile_drift(got),
            # NOT the interior usable volume, which is what this was first
            # called. It is the open area integrated over `compartment_band`
            # only -- the floor fillet below it and the lip region above it are
            # outside the band -- so it understates the usable volume by
            # whatever those contribute. Renamed rather than corrected because
            # the band is what the prismatic predicate reads, and a diagnostic
            # that reports the quantity a predicate actually saw is worth more
            # than one that reports a different quantity under a better name.
            "cavity_area_integrated_over_band_mm3": round(
                sum(got["compartment_cavity_area_mm2"]) *
                geometry["section_step_mm"], 3),
        },
        "request_audit": leak,
        "authoring_root": authoring_root,
        "timings": {
            "harness_seconds": round(sum(clock.values()), 3),
            "harness_breakdown_seconds": clock,
            "design_path_seconds": design_path_seconds,
            "note": "the two are never summed. The harness number is this "
                    "module; the design path is the authoring turn plus "
                    "design-tool run, measured by the caller.",
        },
    }


def render(report: dict[str, Any]) -> str:
    lines = [f"# {report['fixture']} — {report['verdict']}", "",
             f"* fixture revision `{report['fixture_revision']}`",
             f"* candidate `{report['candidate_stl_sha256'][:12]}`",
             f"* reference `{report['reference_sha256'][:12]}`", "",
             "## Hard predicates", "",
             "| predicate | verdict | measured | required |",
             "| --- | --- | --- | --- |"]
    for row in report["hard_predicates"] + report["three_mf"]:
        mark = {True: "PASS", False: "**FAIL**", None: "--"}[row["passes"]]
        lines.append(f"| `{row['predicate']}` | {mark} | "
                     f"{row['measured']} | {row['required']} |")
    clock = report["timings"]
    lines += ["", "## Cost", "",
              f"* harness {clock['harness_seconds']} s",
              f"* design path {clock['design_path_seconds']} s", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="tools/e2e.py",
        description="F1's live end-to-end arm: write the request, or score "
                    "what the real design path returned.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--ask", action="store_true")
    group.add_argument("--score", metavar="CANDIDATE_STL", type=Path)
    parser.add_argument("--into", type=Path, default=None)
    parser.add_argument("--three-mf", type=Path, default=None)
    parser.add_argument("--request", type=Path, default=None)
    parser.add_argument("--design-seconds", type=float, default=None)
    parser.add_argument("--authoring-root", default=None)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    spec = fixture()
    if args.ask:
        if args.into is None:
            parser.error("--ask needs --into <directory>")
        where = write_request(spec, args.into)
        print(f"\n  wrote {where}\n")
        return 0

    try:
        report = score(args.score, args.three_mf, spec,
                       request_dir=args.request,
                       design_path_seconds=args.design_seconds,
                       authoring_root=args.authoring_root)
    except (E2EError, ReferenceUnavailable, ReferenceCorrupt, RequestLeak) as exc:
        sys.stderr.write(f"e2e: {exc}\n")
        return 2
    if args.out:
        args.out.mkdir(parents=True, exist_ok=True)
        (args.out / "result.json").write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\n",
            encoding="utf-8", newline="\n")
        (args.out / "result.md").write_text(render(report), encoding="utf-8",
                                            newline="\n")
    print(render(report))
    return 0 if report["verdict"].startswith("CAD_PASS") else 1


if __name__ == "__main__":
    raise SystemExit(main())
